name: jobs 
on: 
    workflow_dispatch:
jobs:
    job_1:
        runs-on: ubuntu-latest
        steps:
            - name: job 1 and step 1
              run: echo "This is ${{ github.job }}, Step 1" 

    job_2:
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - name: job 2 and step 1    
              run: echo "This is ${{ github.job }}, Step 1"
    job_3:
        runs-on: ubuntu-latest
        needs: job_1
        steps:
            - name: job 3 and step 1    
              run: echo "This is ${{ github.job }}, Step 1"          
