name:  manualworkflow
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'An environment for the manual workflow'
        required: true
        default: "dev"
        type: choice
        options: 
          - dev
          - staging
          - production

        

jobs: 
  manual-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: manual trigger step
        run: echo "This workflow was triggered manually."